version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tx_indexer
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tx_indexer
      - ETHEREUM_RPC_URL=https://mainnet.infura.io/v3/7e4f15896f254690a498bdcef7d59187

volumes:
  pg_data:
